--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE_RETURNS';

SELECT
    SR_RETURN_SHIP_COST AS RETURN_SHIP_COST, 
    SR_RETURN_TAX AS RETURN_TAX, 
    SR_ADDR_SK AS ADDR_SK, 
    SR_REASON_SK AS REASON_SK, 
    SR_RETURN_QUANTITY AS RETURN_QUANTITY, 
    SR_RETURNED_DATE_SK AS RETURNED_DATE_SK, 
    SR_FEE AS FEE, 
    SR_CUSTOMER_SK AS CUSTOMER_SK, 
    SR_STORE_SK AS STORE_SK, 
    SR_RETURN_AMT AS RETURN_AMT, 
    SR_NET_LOSS AS NET_LOSS, 
    SR_RETURN_AMT_INC_TAX AS RETURN_AMT_INC_TAX, 
    SR_REVERSED_CHARGE AS REVERSED_CHARGE, 
    SR_ITEM_SK AS ITEM_SK, 
    SR_TICKET_NUMBER AS TICKET_NUMBER, 
    SR_STORE_CREDIT AS STORE_CREDIT, 
    SR_CDEMO_SK AS CDEMO_SK, 
    SR_RETURN_TIME_SK AS RETURN_TIME_SK, 
    SR_HDEMO_SK AS HDEMO_SK, 
    SR_REFUNDED_CASH AS REFUNDED_CASH
FROM {{ source('raw', 'store_returns') }}