--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 3), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 3), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE';

SELECT COALESCE(S_STORE_NAME,'UNKNOWN') AS STORE_NAME, 
    COALESCE(S_CITY,'UNKNOWN') AS CITY, 
    S_DIVISION_ID AS DIVISION_ID, 
    CAST(S_STORE_SK AS VARCHAR) AS STORE_SK, 
    COALESCE(S_STREET_TYPE,'UNKNOWN') AS STREET_TYPE, 
    COALESCE(S_DIVISION_NAME,'UNKNOWN') AS DIVISION_NAME, 
    S_MARKET_ID AS MARKET_ID, 
    COALESCE(S_ZIP,'UNKNOWN') AS ZIP, 
    COALESCE(S_COUNTY,'UNKNOWN') AS COUNTY, 
    COALESCE(S_COUNTRY,'UNKNOWN') AS COUNTRY,
    COALESCE(S_GEOGRAPHY_CLASS,'UNKNOWN') AS GEOGRAPHY_CLASS, 
    COALESCE(S_MARKET_DESC,'UNKNOWN') AS MARKET_DESC, 
    COALESCE(S_COMPANY_NAME,'UNKNOWN') AS COMPANY_NAME, 
    COALESCE(S_SUITE_NUMBER,'UNKNOWN') AS SUITE_NUMBER, 
    COALESCE(S_STREET_NUMBER,'UNKNOWN') AS STREET_NUMBER, 
    S_REC_START_DATE AS REC_START_DATE, 
    COALESCE(S_TAX_PRECENTAGE, 0) AS TAX_PRECENTAGE, 
    COALESCE(S_NUMBER_EMPLOYEES, 0) AS NUMBER_EMPLOYEES, 
    S_STORE_ID AS STORE_ID, 
    S_COMPANY_ID AS COMPANY_ID, 
    COALESCE(S_STREET_NAME,'UNKNOWN') AS STREET_NAME, 
    COALESCE(S_MANAGER,'UNKNOWN') AS MANAGER, 
    S_GMT_OFFSET AS GMT_OFFSET, 
    COALESCE(S_MARKET_MANAGER,'UNKNOWN') AS MARKET_MANAGER, 
    S_REC_END_DATE AS REC_END_DATE, 
    CASE WHEN rec_end_date IS NOT NULL 
    THEN 1 
    ELSE 0 
    END AS IS_CURENT,
    CAST(S_CLOSED_DATE_SK AS VARCHAR) AS CLOSED_DATE_SK, 
    COALESCE(S_STATE,'UNKNOWN') AS STATE, 
    COALESCE(S_HOURS,'UNKNOWN') AS HOURS, 
    COALESCE(S_FLOOR_SPACE, 0) AS FLOOR_SPACE

FROM {{ source('raw', 'store') }}

