--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE_SALES';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE_SALES';

SELECT
    CAST(SS_SOLD_TIME_SK AS VARCHAR) AS SOLD_TIME_SK, 
    COALESCE(SS_EXT_SALES_PRICE, 0) AS EXT_SALES_PRICE, 
    COALESCE(SS_EXT_DISCOUNT_AMT, 0) AS EXT_DISCOUNT_AMT, 
    CAST(SS_STORE_SK AS VARCHAR) AS STORE_SK, 
    SS_TICKET_NUMBER AS TICKET_NUMBER, 
    COALESCE(SS_EXT_LIST_PRICE, 0) AS EXT_LIST_PRICE, 
    COALESCE(SS_WHOLESALE_COST, 0) AS WHOLESALE_COST, 
    COALESCE(SS_NET_PROFIT, 0) AS NET_PROFIT, 
    CAST(SS_ITEM_SK AS VARCHAR) AS ITEM_SK, 
    CAST(SS_CUSTOMER_SK AS VARCHAR) AS CUSTOMER_SK, 
    CAST(SS_PROMO_SK AS VARCHAR) AS PROMO_SK, 
    COALESCE(SS_EXT_WHOLESALE_COST, 0) AS EXT_WHOLESALE_COST, 
    CAST(SS_CDEMO_SK AS VARCHAR) AS CDEMO_SK, 
    COALESCE(SS_QUANTITY, 0) AS QUANTITY, 
    CAST(SS_ADDR_SK AS VARCHAR) AS ADDR_SK, 
    COALESCE(SS_EXT_TAX, 0) AS EXT_TAX, 
    CAST(SS_SOLD_DATE_SK AS VARCHAR) AS SOLD_DATE_SK, 
    COALESCE(SS_NET_PAID_INC_TAX, 0) AS NET_PAID_INC_TAX, 
    COALESCE(SS_SALES_PRICE, 0) AS SALES_PRICE, 
    COALESCE(SS_NET_PAID, 0) AS NET_PAID, 
    COALESCE(SS_LIST_PRICE, 0) AS LIST_PRICE, 
    CAST(SS_HDEMO_SK AS VARCHAR) AS HDEMO_SK, 
    COALESCE(SS_COUPON_AMT, 0) AS COUPON_AMT
FROM {{ source('raw', 'store_sales') }}