--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CUSTOMER_DEMOGRAPHICS';

SELECT
    CD_MARITAL_STATUS AS MARITAL_STATUS,
    CD_DEP_COUNT AS DEP_COUNT,
    CD_EDUCATION_STATUS AS EDUCATION_STATUS,
    CD_GENDER AS GENDER,
    CD_PURCHASE_ESTIMATE AS PURCHASE_ESTIMATE,
    CD_CREDIT_RATING AS CREDIT_RATING,
    CAST(CD_DEMO_SK AS VARCHAR) AS DEMO_SK,
    CD_DEP_EMPLOYED_COUNT AS DEP_EMPLOYED_COUNT,
    CD_DEP_COLLEGE_COUNT AS DEP_COLLEGE_COUNT
FROM {{ source('raw', 'customer_demographics') }}