--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 3), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CUSTOMER';

SELECT
    CAST(C_FIRST_SALES_DATE_SK AS VARCHAR) AS FIRST_SALES_DATE_SK,
    C_BIRTH_YEAR AS BIRTH_YEAR,
    COALESCE(C_PREFERRED_CUST_FLAG,'N') AS PREFERRED_CUST_FLAG,
    CAST(C_CURRENT_HDEMO_SK AS VARCHAR) AS CURRENT_HDEMO_SK,
    COALESCE(C_EMAIL_ADDRESS, 'NOT_PROVIDED') AS EMAIL_ADDRESS,
    COALESCE(C_FIRST_NAME,'UNKNOWN') AS FIRST_NAME,
    C_LAST_REVIEW_DATE AS LAST_REVIEW_DATE,
    C_BIRTH_MONTH AS BIRTH_MONTH,
    CAST(C_CURRENT_CDEMO_SK AS VARCHAR) AS CURRENT_CDEMO_SK,
    CAST(C_FIRST_SHIPTO_DATE_SK AS VARCHAR) AS FIRST_SHIPTO_DATE_SK,
    COALESCE(C_SALUTATION,'UNKNOWN') AS SALUTATION,
    CAST(C_CURRENT_ADDR_SK AS VARCHAR) AS CURRENT_ADDR_SK,
    C_CUSTOMER_ID AS CUSTOMER_ID,
    CAST(C_CUSTOMER_SK AS VARCHAR) AS CUSTOMER_SK,
    COALESCE(C_LOGIN,'UNKNOWN') AS LOGIN,
    C_BIRTH_DAY AS BIRTH_DAY,
    COALESCE(C_BIRTH_COUNTRY,'UNKNOWN') AS BIRTH_COUNTRY,
    COALESCE(C_LAST_NAME,'UNKNOWN') AS LAST_NAME
FROM {{ source('raw', 'customer') }}

