--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'HOUSEHOLD_DEMOGRAPHICS';

SELECT
    HD_BUY_POTENTIAL AS BUY_POTENTIAL,
    HD_VEHICLE_COUNT AS VEHICLE_COUNT,
    HD_INCOME_BAND_SK AS INCOME_BAND_SK,
    HD_DEP_COUNT AS DEP_COUNT,
    HD_DEMO_SK AS DEMO_SK
FROM {{ source('raw', 'household_demographics') }}