--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 3), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'DATE_DIM';

SELECT
    D_FY_QUARTER_SEQ AS FY_QUARTER_SEQ,
    D_DOW AS DOW,
    D_FOLLOWING_HOLIDAY AS FOLLOWING_HOLIDAY,
    D_DATE AS DATE,
    D_MONTH_SEQ AS MONTH_SEQ,
    D_DAY_NAME AS DAY_NAME,
    D_CURRENT_YEAR AS CURRENT_YEAR,
    D_YEAR AS YEAR,
    D_MOY AS MOY,
    D_WEEKEND AS WEEKEND,
    D_CURRENT_MONTH AS CURRENT_MONTH,
    D_FY_YEAR AS FY_YEAR,
    D_HOLIDAY AS HOLIDAY,
    D_QUARTER_SEQ AS QUARTER_SEQ,
    D_SAME_DAY_LY AS SAME_DAY_LY,
    D_CURRENT_WEEK AS CURRENT_WEEK,
    D_CURRENT_DAY AS CURRENT_DAY,
    D_QOY AS QOY,
    D_WEEK_SEQ AS WEEK_SEQ,
    D_LAST_DOM AS LAST_DOM,
    D_QUARTER_NAME AS QUARTER_NAME,
    D_DOM AS DOM,
    D_SAME_DAY_LQ AS SAME_DAY_LQ,
    D_FY_WEEK_SEQ AS FY_WEEK_SEQ,
    D_CURRENT_QUARTER AS CURRENT_QUARTER,
    D_DATE_ID AS DATE_ID,
    D_FIRST_DOM AS FIRST_DOM,
    CAST(D_DATE_SK AS VARCHAR) AS DATE_SK
FROM {{ source('raw', 'date_dim') }}