--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE_SALES';

SELECT
    CAST(SS_SOLD_TIME_SK AS VARCHAR) AS SOLD_TIME_SK, 
    SS_EXT_SALES_PRICE AS EXT_SALES_PRICE, 
    SS_EXT_DISCOUNT_AMT AS EXT_DISCOUNT_AMT, 
    CAST(SS_STORE_SK AS VARCHAR) AS STORE_SK, 
    SS_TICKET_NUMBER AS TICKET_NUMBER, 
    SS_EXT_LIST_PRICE AS EXT_LIST_PRICE, 
    SS_WHOLESALE_COST AS WHOLESALE_COST, 
    SS_NET_PROFIT AS NET_PROFIT, 
    CAST(SS_ITEM_SK AS VARCHAR) AS ITEM_SK, 
    CAST(SS_CUSTOMER_SK AS VARCHAR) AS CUSTOMER_SK, 
    CAST(SS_PROMO_SK AS VARCHAR) AS PROMO_SK, 
    SS_EXT_WHOLESALE_COST AS EXT_WHOLESALE_COST, 
    CAST(SS_CDEMO_SK AS VARCHAR) AS CDEMO_SK, 
    SS_QUANTITY AS QUANTITY, 
    CAST(SS_ADDR_SK AS VARCHAR) AS ADDR_SK, 
    SS_EXT_TAX AS EXT_TAX, 
    CAST(SS_SOLD_DATE_SK AS VARCHAR) AS SOLD_DATE_SK, 
    SS_NET_PAID_INC_TAX AS NET_PAID_INC_TAX, 
    SS_SALES_PRICE AS SALES_PRICE, 
    SS_NET_PAID AS NET_PAID, 
    SS_LIST_PRICE AS LIST_PRICE, 
    CAST(SS_HDEMO_SK AS VARCHAR) AS HDEMO_SK, 
    SS_COUPON_AMT AS COUPON_AMT
FROM {{ source('raw', 'store_sales') }}