--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CATALOG_RETURNS';

SELECT
    CR_REVERSED_CHARGE AS REVERSED_CHARGE, 
    CR_REFUNDED_CDEMO_SK AS REFUNDED_CDEMO_SK, 
    CR_NET_LOSS AS NET_LOSS, 
    CR_WAREHOUSE_SK AS WAREHOUSE_SK, 
    CR_ITEM_SK AS ITEM_SK, 
    CR_CALL_CENTER_SK AS CALL_CENTER_SK, 
    CR_SHIP_MODE_SK AS SHIP_MODE_SK, 
    CR_RETURNED_DATE_SK AS RETURNED_DATE_SK, 
    CR_REFUNDED_CUSTOMER_SK AS REFUNDED_CUSTOMER_SK, 
    CR_RETURNING_CUSTOMER_SK AS RETURNING_CUSTOMER_SK, 
    CR_STORE_CREDIT AS STORE_CREDIT, 
    CR_ORDER_NUMBER AS ORDER_NUMBER, 
    CR_REFUNDED_CASH AS REFUNDED_CASH, 
    CR_RETURNING_HDEMO_SK AS RETURNING_HDEMO_SK, 
    CR_RETURNING_ADDR_SK AS RETURNING_ADDR_SK, 
    CR_CATALOG_PAGE_SK AS CATALOG_PAGE_SK, 
    CR_REFUNDED_ADDR_SK AS REFUNDED_ADDR_SK, 
    CR_RETURN_TAX AS RETURN_TAX, 
    CR_RETURN_AMOUNT AS RETURN_AMOUNT, 
    CR_RETURN_SHIP_COST AS RETURN_SHIP_COST, 
    CR_RETURNED_TIME_SK AS RETURNED_TIME_SK, 
    CR_RETURN_QUANTITY AS RETURN_QUANTITY, 
    CR_RETURN_AMT_INC_TAX AS RETURN_AMT_INC_TAX, 
    CR_REASON_SK AS REASON_SK, 
    CR_FEE AS FEE, 
    CR_REFUNDED_HDEMO_SK AS REFUNDED_HDEMO_SK, 
    CR_RETURNING_CDEMO_SK AS RETURNING_CDEMO_SK
FROM {{ source('raw', 'catalog_returns') }}