--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 3), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE';

select S_STREET_TYPE AS STREET_TYPE, 
    S_DIVISION_NAME AS DIVISION_NAME, 
    S_MARKET_ID AS MARKET_ID, 
    S_ZIP AS ZIP, 
    S_COUNTY AS COUNTY, 
    S_COUNTRY AS COUNTRY,
    S_GEOGRAPHY_CLASS AS GEOGRAPHY_CLASS, 
    S_MARKET_DESC AS MARKET_DESC, 
    S_STORE_NAME AS STORE_NAME, 
    S_CITY AS CITY, 
    S_DIVISION_ID AS DIVISION_ID, 
    CAST(S_STORE_SK AS VARCHAR) AS STORE_SK, 
    S_COMPANY_NAME AS COMPANY_NAME, 
    S_SUITE_NUMBER AS SUITE_NUMBER, 
    S_STREET_NUMBER AS STREET_NUMBER, 
    S_REC_START_DATE AS REC_START_DATE, 
    S_TAX_PRECENTAGE AS TAX_PRECENTAGE, 
    S_NUMBER_EMPLOYEES AS NUMBER_EMPLOYEES, 
    S_STORE_ID AS STORE_ID, 
    S_COMPANY_ID AS COMPANY_ID, 
    S_STREET_NAME AS STREET_NAME, 
    S_MANAGER AS MANAGER, 
    S_GMT_OFFSET AS GMT_OFFSET, 
    S_MARKET_MANAGER AS MARKET_MANAGER, 
    S_REC_END_DATE AS REC_END_DATE, 
    CAST(S_CLOSED_DATE_SK AS VARCHAR) AS CLOSED_DATE_SK, 
    S_STATE AS STATE, 
    S_HOURS AS HOURS, 
    S_FLOOR_SPACE AS FLOOR_SPACE

from {{ source('raw', 'store') }}

