--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CATALOG_RETURNS';


SELECT
    COALESCE(CR_REVERSED_CHARGE, 0) AS REVERSED_CHARGE, 
    CAST(CR_REFUNDED_CDEMO_SK AS VARCHAR) AS REFUNDED_CDEMO_SK, 
    COALESCE(CR_NET_LOSS, 0) AS NET_LOSS, 
    CAST(CR_WAREHOUSE_SK AS VARCHAR) AS WAREHOUSE_SK, 
    CAST(CR_ITEM_SK AS VARCHAR) AS ITEM_SK, 
    CAST(CR_CALL_CENTER_SK AS VARCHAR) AS CALL_CENTER_SK, 
    CAST(CR_SHIP_MODE_SK AS VARCHAR) AS SHIP_MODE_SK, 
    CAST(CR_RETURNED_DATE_SK AS VARCHAR) AS RETURNED_DATE_SK, 
    CAST(CR_REFUNDED_CUSTOMER_SK AS VARCHAR) AS REFUNDED_CUSTOMER_SK, 
    CAST(CR_RETURNING_CUSTOMER_SK AS VARCHAR) AS RETURNING_CUSTOMER_SK, 
    COALESCE(CR_STORE_CREDIT, 0) AS STORE_CREDIT, 
    CR_ORDER_NUMBER AS ORDER_NUMBER, 
    COALESCE(CR_REFUNDED_CASH, 0) AS REFUNDED_CASH, 
    CAST(CR_RETURNING_HDEMO_SK AS VARCHAR) AS RETURNING_HDEMO_SK, 
    CAST(CR_RETURNING_ADDR_SK AS VARCHAR) AS RETURNING_ADDR_SK, 
    CAST(CR_CATALOG_PAGE_SK AS VARCHAR) AS CATALOG_PAGE_SK, 
    CAST(CR_REFUNDED_ADDR_SK AS VARCHAR) AS REFUNDED_ADDR_SK, 
    COALESCE(CR_RETURN_TAX, 0) AS RETURN_TAX, 
    COALESCE(CR_RETURN_AMOUNT, 0) AS RETURN_AMOUNT, 
    COALESCE(CR_RETURN_SHIP_COST, 0) AS RETURN_SHIP_COST, 
    CAST(CR_RETURNED_TIME_SK AS VARCHAR) AS RETURNED_TIME_SK, 
    COALESCE(CR_RETURN_QUANTITY, 0) AS RETURN_QUANTITY, 
    COALESCE(CR_RETURN_AMT_INC_TAX, 0) AS RETURN_AMT_INC_TAX, 
    CAST(CR_REASON_SK AS VARCHAR) AS REASON_SK, 
    COALESCE(CR_FEE, 0) AS FEE, 
    CAST(CR_REFUNDED_HDEMO_SK AS VARCHAR) AS REFUNDED_HDEMO_SK, 
    CAST(CR_RETURNING_CDEMO_SK AS VARCHAR) AS RETURNING_CDEMO_SK
FROM {{ source('raw', 'catalog_returns') }}