--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'WEB_SALES';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'WEB_SALES';

SELECT
    CAST(WS_SHIP_CUSTOMER_SK AS VARCHAR) AS SHIP_CUSTOMER_SK, 
    CAST(WS_WEB_PAGE_SK AS VARCHAR) AS WEB_PAGE_SK, 
    CAST(WS_WEB_SITE_SK AS VARCHAR) AS WEB_SITE_SK, 
    COALESCE(WS_NET_PROFIT, 0) AS NET_PROFIT, 
    COALESCE(WS_NET_PAID, 0) AS NET_PAID, 
    COALESCE(WS_SALES_PRICE, 0) AS SALES_PRICE, 
    WS_ORDER_NUMBER AS ORDER_NUMBER, 
    CAST(WS_WAREHOUSE_SK AS VARCHAR) AS WAREHOUSE_SK, 
    CAST(WS_SOLD_DATE_SK AS VARCHAR) AS SOLD_DATE_SK, 
    COALESCE(WS_EXT_LIST_PRICE, 0) AS EXT_LIST_PRICE, 
    CAST(WS_BILL_ADDR_SK AS VARCHAR) AS BILL_ADDR_SK, 
    CAST(WS_BILL_HDEMO_SK AS VARCHAR) AS BILL_HDEMO_SK, 
    COALESCE(WS_EXT_SALES_PRICE, 0) AS EXT_SALES_PRICE, 
    CAST(WS_BILL_CDEMO_SK AS VARCHAR) AS BILL_CDEMO_SK, 
    CAST(WS_ITEM_SK AS VARCHAR) AS ITEM_SK, 
    COALESCE(WS_LIST_PRICE, 0) AS LIST_PRICE, 
    CAST(WS_SHIP_CDEMO_SK AS VARCHAR) AS SHIP_CDEMO_SK, 
    CAST(WS_SHIP_ADDR_SK AS VARCHAR) AS SHIP_ADDR_SK, 
    COALESCE(WS_EXT_TAX, 0) AS EXT_TAX, 
    CAST(WS_BILL_CUSTOMER_SK AS VARCHAR) AS BILL_CUSTOMER_SK, 
    CAST(WS_SOLD_TIME_SK AS VARCHAR) AS SOLD_TIME_SK, 
    CAST(WS_SHIP_DATE_SK AS VARCHAR) AS SHIP_DATE_SK, 
    CAST(WS_PROMO_SK AS VARCHAR) AS PROMO_SK, 
    CAST(WS_SHIP_HDEMO_SK AS VARCHAR) AS SHIP_HDEMO_SK, 
    COALESCE(WS_NET_PAID_INC_TAX, 0) AS NET_PAID_INC_TAX, 
    COALESCE(WS_NET_PAID_INC_SHIP, 0) AS NET_PAID_INC_SHIP, 
    COALESCE(WS_EXT_SHIP_COST, 0) AS EXT_SHIP_COST, 
    COALESCE(WS_COUPON_AMT, 0) AS COUPON_AMT, 
    COALESCE(WS_EXT_WHOLESALE_COST, 0) AS EXT_WHOLESALE_COST, 
    COALESCE(WS_NET_PAID_INC_SHIP_TAX, 0) AS NET_PAID_INC_SHIP_TAX, 
    COALESCE(WS_EXT_DISCOUNT_AMT, 0) AS EXT_DISCOUNT_AMT, 
    COALESCE(WS_WHOLESALE_COST, 0) AS WHOLESALE_COST, 
    CAST(WS_SHIP_MODE_SK AS VARCHAR) AS SHIP_MODE_SK, 
    COALESCE(WS_QUANTITY, 0) AS QUANTITY
FROM {{ source('raw', 'web_sales') }}