--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'HOUSEHOLD_DEMOGRAPHICS';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'HOUSEHOLD_DEMOGRAPHICS';

SELECT
    COALESCE(HD_BUY_POTENTIAL,'UNKNOWN') AS BUY_POTENTIAL,
    COALESCE(HD_VEHICLE_COUNT, 0) AS VEHICLE_COUNT,
    CAST(HD_INCOME_BAND_SK AS VARCHAR) AS INCOME_BAND_SK,
    COALESCE(HD_DEP_COUNT, 0) AS DEP_COUNT,
    CAST(HD_DEMO_SK AS VARCHAR) AS DEMO_SK
FROM {{ source('raw', 'household_demographics') }}