--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 5), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'INVENTORY';

SELECT
    CAST(INV_WAREHOUSE_SK AS VARCHAR) AS WAREHOUSE_SK,
    INV_DATE_SK AS DATE_SK,
    INV_QUANTITY_ON_HAND AS QUANTITY_ON_HAND,
    CAST(INV_ITEM_SK AS VARCHAR) AS ITEM_SK
FROM {{ source('raw', 'inventory') }}