--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'WEB_RETURNS';

SELECT
    WR_REASON_SK AS REASON_SK,
    WR_WEB_PAGE_SK AS WEB_PAGE_SK,
    WR_RETURNING_CUSTOMER_SK AS RETURNING_CUSTOMER_SK,
    WR_RETURNING_HDEMO_SK AS RETURNING_HDEMO_SK,
    WR_REFUNDED_HDEMO_SK AS REFUNDED_HDEMO_SK,
    WR_REFUNDED_CDEMO_SK AS REFUNDED_CDEMO_SK,
    WR_RETURN_AMT_INC_TAX AS RETURN_AMT_INC_TAX,
    WR_RETURNING_ADDR_SK AS RETURNING_ADDR_SK,
    WR_FEE AS FEE,
    WR_RETURN_SHIP_COST AS RETURN_SHIP_COST,
    WR_RETURNED_DATE_SK AS RETURNED_DATE_SK,
    WR_REFUNDED_CASH AS REFUNDED_CASH,
    WR_REFUNDED_ADDR_SK AS REFUNDED_ADDR_SK,
    WR_RETURN_AMT AS RETURN_AMT,
    WR_RETURN_TAX AS RETURN_TAX,
    WR_ACCOUNT_CREDIT AS ACCOUNT_CREDIT,
    WR_RETURN_QUANTITY AS RETURN_QUANTITY,
    WR_NET_LOSS AS NET_LOSS,
    WR_ORDER_NUMBER AS ORDER_NUMBER,
    WR_REVERSED_CHARGE AS REVERSED_CHARGE,
    WR_RETURNING_CDEMO_SK AS RETURNING_CDEMO_SK,
    WR_REFUNDED_CUSTOMER_SK AS REFUNDED_CUSTOMER_SK,
    WR_ITEM_SK AS ITEM_SK,
    WR_RETURNED_TIME_SK AS RETURNED_TIME_SK
FROM {{ source('raw', 'web_returns') }}