--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CATALOG_RETURNS';

SELECT
    CR_REVERSED_CHARGE AS REVERSED_CHARGE, 
    CAST(CR_REFUNDED_CDEMO_SK AS VARCHAR) AS REFUNDED_CDEMO_SK, 
    CR_NET_LOSS AS NET_LOSS, 
    CAST(CR_WAREHOUSE_SK AS VARCHAR) AS WAREHOUSE_SK, 
    CAST(CR_ITEM_SK AS VARCHAR) AS ITEM_SK, 
    CAST(CR_CALL_CENTER_SK AS VARCHAR) AS CALL_CENTER_SK, 
    CAST(CR_SHIP_MODE_SK AS VARCHAR) AS SHIP_MODE_SK, 
    CAST(CR_RETURNED_DATE_SK AS VARCHAR) AS RETURNED_DATE_SK, 
    CAST(CR_REFUNDED_CUSTOMER_SK AS VARCHAR) AS REFUNDED_CUSTOMER_SK, 
    CAST(CR_RETURNING_CUSTOMER_SK AS VARCHAR) AS RETURNING_CUSTOMER_SK, 
    CR_STORE_CREDIT AS STORE_CREDIT, 
    CR_ORDER_NUMBER AS ORDER_NUMBER, 
    CR_REFUNDED_CASH AS REFUNDED_CASH, 
    CAST(CR_RETURNING_HDEMO_SK AS VARCHAR) AS RETURNING_HDEMO_SK, 
    CAST(CR_RETURNING_ADDR_SK AS VARCHAR) AS RETURNING_ADDR_SK, 
    CAST(CR_CATALOG_PAGE_SK AS VARCHAR) AS CATALOG_PAGE_SK, 
    CAST(CR_REFUNDED_ADDR_SK AS VARCHAR) AS REFUNDED_ADDR_SK, 
    CR_RETURN_TAX AS RETURN_TAX, 
    CR_RETURN_AMOUNT AS RETURN_AMOUNT, 
    CR_RETURN_SHIP_COST AS RETURN_SHIP_COST, 
    CAST(CR_RETURNED_TIME_SK AS VARCHAR) AS RETURNED_TIME_SK, 
    CR_RETURN_QUANTITY AS RETURN_QUANTITY, 
    CR_RETURN_AMT_INC_TAX AS RETURN_AMT_INC_TAX, 
    CAST(CR_REASON_SK AS VARCHAR) AS REASON_SK, 
    CR_FEE AS FEE, 
    CAST(CR_REFUNDED_HDEMO_SK AS VARCHAR) AS REFUNDED_HDEMO_SK, 
    CAST(CR_RETURNING_CDEMO_SK AS VARCHAR) AS RETURNING_CDEMO_SK
FROM {{ source('raw', 'catalog_returns') }}