--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'WEB_RETURNS';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'WEB_RETURNS';

SELECT
    CAST(WR_REASON_SK AS VARCHAR) AS REASON_SK,
    CAST(WR_WEB_PAGE_SK AS VARCHAR) AS WEB_PAGE_SK,
    CAST(WR_RETURNING_CUSTOMER_SK AS VARCHAR) AS RETURNING_CUSTOMER_SK,
    CAST(WR_RETURNING_HDEMO_SK AS VARCHAR) AS RETURNING_HDEMO_SK,
    CAST(WR_REFUNDED_HDEMO_SK AS VARCHAR) AS REFUNDED_HDEMO_SK,
    CAST(WR_REFUNDED_CDEMO_SK AS VARCHAR) AS REFUNDED_CDEMO_SK,
    COALESCE(WR_RETURN_AMT_INC_TAX, 0) AS RETURN_AMT_INC_TAX,
    CAST(WR_RETURNING_ADDR_SK AS VARCHAR) AS RETURNING_ADDR_SK,
    COALESCE(WR_FEE, 0) AS FEE,
    COALESCE(WR_RETURN_SHIP_COST, 0) AS RETURN_SHIP_COST,
    CAST(WR_RETURNED_DATE_SK AS VARCHAR) AS RETURNED_DATE_SK,
    COALESCE(WR_REFUNDED_CASH, 0) AS REFUNDED_CASH,
    CAST(WR_REFUNDED_ADDR_SK AS VARCHAR) AS REFUNDED_ADDR_SK,
    COALESCE(WR_RETURN_AMT, 0) AS RETURN_AMT,
    COALESCE(WR_RETURN_TAX, 0) AS RETURN_TAX,
    COALESCE(WR_ACCOUNT_CREDIT, 0) AS ACCOUNT_CREDIT,
    COALESCE(WR_RETURN_QUANTITY, 0) AS RETURN_QUANTITY,
    COALESCE(WR_NET_LOSS, 0) AS NET_LOSS,
    WR_ORDER_NUMBER AS ORDER_NUMBER,
    COALESCE(WR_REVERSED_CHARGE, 0) AS REVERSED_CHARGE,
    CAST(WR_RETURNING_CDEMO_SK AS VARCHAR) AS RETURNING_CDEMO_SK,
    CAST(WR_REFUNDED_CUSTOMER_SK AS VARCHAR) AS REFUNDED_CUSTOMER_SK,
    CAST(WR_ITEM_SK AS VARCHAR) AS ITEM_SK,
    CAST(WR_RETURNED_TIME_SK AS VARCHAR) AS RETURNED_TIME_SK
FROM {{ source('raw', 'web_returns') }}