--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ', ')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE_RETURNS';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'STORE_RETURNS';

SELECT
    COALESCE(SR_RETURN_SHIP_COST, 0) AS RETURN_SHIP_COST, 
    COALESCE(SR_RETURN_TAX, 0) AS RETURN_TAX, 
    CAST(SR_ADDR_SK AS VARCHAR) AS ADDR_SK, 
    SR_REASON_SK AS REASON_SK, 
    COALESCE(SR_RETURN_QUANTITY, 0) AS RETURN_QUANTITY, 
    CAST(SR_RETURNED_DATE_SK AS VARCHAR) AS RETURNED_DATE_SK, 
    COALESCE(SR_FEE, 0) AS FEE, 
    CAST(SR_CUSTOMER_SK AS VARCHAR) AS CUSTOMER_SK, 
    CAST(SR_STORE_SK AS VARCHAR) AS STORE_SK, 
    COALESCE(SR_RETURN_AMT, 0) AS RETURN_AMT, 
    COALESCE(SR_NET_LOSS, 0) AS NET_LOSS, 
    COALESCE(SR_RETURN_AMT_INC_TAX, 0) AS RETURN_AMT_INC_TAX, 
    COALESCE(SR_REVERSED_CHARGE, 0) AS REVERSED_CHARGE, 
    CAST(SR_ITEM_SK AS VARCHAR) AS ITEM_SK, 
    SR_TICKET_NUMBER AS TICKET_NUMBER, 
    COALESCE(SR_STORE_CREDIT, 0) AS STORE_CREDIT, 
    CAST(SR_CDEMO_SK AS VARCHAR) AS CDEMO_SK, 
    CAST(SR_RETURN_TIME_SK AS VARCHAR) AS RETURN_TIME_SK, 
    CAST(SR_HDEMO_SK AS VARCHAR) AS HDEMO_SK, 
    COALESCE(SR_REFUNDED_CASH, 0) AS REFUNDED_CASH
FROM {{ source('raw', 'store_returns') }}