--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 3), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'WAREHOUSE';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 3), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'WAREHOUSE';

SELECT
    W_WAREHOUSE_SQ_FT AS WAREHOUSE_SQ_FT,
    COALESCE(W_SUITE_NUMBER, 'UNKNOWN') AS SUITE_NUMBER,
    W_WAREHOUSE_ID AS WAREHOUSE_ID,
    COALESCE(W_COUNTRY, 'UNKNOWN') AS COUNTRY,
    COALESCE(W_STREET_NUMBER, 'UNKNOWN') AS STREET_NUMBER,
    COALESCE(W_WAREHOUSE_NAME, 'UNKNOWN') AS WAREHOUSE_NAME,
    COALESCE(W_ZIP, 'UNKNOWN') AS ZIP,
    COALESCE(W_STREET_NAME, 'UNKNOWN') AS STREET_NAME,
    COALESCE(W_STREET_TYPE, 'UNKNOWN') AS STREET_TYPE,
    CAST(W_WAREHOUSE_SK AS VARCHAR) AS WAREHOUSE_SK,
    W_GMT_OFFSET AS GMT_OFFSET,
    COALESCE(W_COUNTY, 'UNKNOWN') AS COUNTY,
    COALESCE(W_CITY, 'UNKNOWN') AS CITY,
    COALESCE(W_STATE, 'UNKNOWN') AS STATE
FROM {{ source('raw', 'warehouse') }}