--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 3), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'ITEM';

SELECT
    I_FORMULATION AS FORMULATION,
    I_ITEM_ID AS ITEM_ID,
    I_BRAND_ID AS BRAND_ID,
    I_REC_START_DATE AS REC_START_DATE,
    I_CURRENT_PRICE AS CURRENT_PRICE,
    I_MANUFACT AS MANUFACT,
    CAST(I_ITEM_SK AS VARCHAR) AS ITEM_SK,
    I_COLOR AS COLOR,
    I_CATEGORY_ID AS CATEGORY_ID,
    I_SIZE AS SIZE,
    I_REC_END_DATE AS REC_END_DATE,
    I_UNITS AS UNITS,
    I_BRAND AS BRAND,
    I_WHOLESALE_COST AS WHOLESALE_COST,
    I_PRODUCT_NAME AS PRODUCT_NAME,
    I_ITEM_DESC AS ITEM_DESC,
    I_CLASS_ID AS CLASS_ID,
    I_CLASS AS CLASS,
    I_MANUFACT_ID AS MANUFACT_ID,
    I_CONTAINER AS CONTAINER,
    I_CATEGORY AS CATEGORY,
    I_MANAGER_ID AS MANAGER_ID
FROM {{ source('raw', 'item') }}