--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CUSTOMER_ADDRESS';

SELECT
    CA_SUITE_NUMBER AS SUITE_NUMBER,
    CA_LOCATION_TYPE AS LOCATION_TYPE,
    CA_STATE AS STATE,
    CA_STREET_TYPE AS STREET_TYPE,
    CAST(CA_ADDRESS_SK AS VARCHAR) AS ADDRESS_SK,
    CA_COUNTY AS COUNTY,
    CA_STREET_NUMBER AS STREET_NUMBER,
    CA_COUNTRY AS COUNTRY,
    CA_GMT_OFFSET AS GMT_OFFSET,
    CA_CITY AS CITY,
    CA_ADDRESS_ID AS ADDRESS_ID,
    CA_ZIP AS ZIP,
    CA_STREET_NAME AS STREET_NAME
FROM {{ source('raw', 'customer_address') }}