--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 4), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CUSTOMER_DEMOGRAPHICS';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CUSTOMER_DEMOGRAPHICS';

SELECT
    COALESCE(CD_MARITAL_STATUS,'UNKNOWN') AS MARITAL_STATUS,
    COALESCE(CD_DEP_COUNT, 0) AS DEP_COUNT,
    COALESCE(CD_EDUCATION_STATUS,'UNKNOWN') AS EDUCATION_STATUS,
    COALESCE(CD_GENDER,'UNKNOWN') AS GENDER,
    COALESCE(CD_PURCHASE_ESTIMATE, 0) AS PURCHASE_ESTIMATE,
    COALESCE(CD_CREDIT_RATING,'UNKNOWN') AS CREDIT_RATING,
    CAST(CD_DEMO_SK AS VARCHAR) AS DEMO_SK,
    COALESCE(CD_DEP_EMPLOYED_COUNT, 0) AS DEP_EMPLOYED_COUNT,
    COALESCE(CD_DEP_COLLEGE_COUNT, 0) AS DEP_COLLEGE_COUNT
FROM {{ source('raw', 'customer_demographics') }}