--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 3), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CUSTOMER';

SELECT
    CAST(C_FIRST_SALES_DATE_SK AS VARCHAR) AS FIRST_SALES_DATE_SK,
    C_BIRTH_YEAR AS BIRTH_YEAR,
    C_PREFERRED_CUST_FLAG AS PREFERRED_CUST_FLAG,
    CAST(C_CURRENT_HDEMO_SK AS VARCHAR) AS CURRENT_HDEMO_SK,
    C_EMAIL_ADDRESS AS EMAIL_ADDRESS,
    C_FIRST_NAME AS FIRST_NAME,
    C_LAST_REVIEW_DATE AS LAST_REVIEW_DATE,
    C_BIRTH_MONTH AS BIRTH_MONTH,
    CAST(C_CURRENT_CDEMO_SK AS VARCHAR) AS CURRENT_CDEMO_SK,
    CAST(C_FIRST_SHIPTO_DATE_SK AS VARCHAR) AS FIRST_SHIPTO_DATE_SK,
    C_SALUTATION AS SALUTATION,
    CAST(C_CURRENT_ADDR_SK AS VARCHAR) AS CURRENT_ADDR_SK,
    C_CUSTOMER_ID AS CUSTOMER_ID,
    CAST(C_CUSTOMER_SK AS VARCHAR) AS CUSTOMER_SK,
    C_LOGIN AS LOGIN,
    C_BIRTH_DAY AS BIRTH_DAY,
    C_BIRTH_COUNTRY AS BIRTH_COUNTRY,
    C_LAST_NAME AS LAST_NAME
FROM {{ source('raw', 'customer') }}

