--SELECT LISTAGG(COLUMN_NAME || ' AS ' || SUBSTR(COLUMN_NAME, 3), ',\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'ITEM';

--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 3), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'ITEM';

SELECT
    COALESCE(I_FORMULATION,'UNKNOWN') AS FORMULATION,
    I_ITEM_ID AS ITEM_ID,
    I_BRAND_ID AS BRAND_ID,
    I_REC_START_DATE AS REC_START_DATE,
    COALESCE(I_CURRENT_PRICE, 0) AS CURRENT_PRICE,
    COALESCE(I_MANUFACT, 'UNKNOWN') AS MANUFACT,
    CAST(I_ITEM_SK AS VARCHAR) AS ITEM_SK,
    COALESCE(I_COLOR,'UNKNOWN') AS COLOR,
    I_CATEGORY_ID AS CATEGORY_ID,
    COALESCE(I_SIZE,'UNKNOWN') AS SIZE,
    I_REC_END_DATE AS REC_END_DATE,
    CASE WHEN rec_end_date IS NOT NULL 
    THEN 1 
    ELSE 0 
    END AS IS_CURENT,
    COALESCE(I_UNITS,'UNKNOWN') AS UNITS,
    COALESCE(I_BRAND,'UNKNOWN') AS BRAND,
    COALESCE(I_WHOLESALE_COST, 0) AS WHOLESALE_COST,
    COALESCE(I_PRODUCT_NAME,'UNKNOWN') AS PRODUCT_NAME,
    COALESCE(I_ITEM_DESC,'UNKNOWN') AS ITEM_DESC,
    I_CLASS_ID AS CLASS_ID,
    COALESCE(I_CLASS,'UNKNOWN') AS CLASS,
    I_MANUFACT_ID AS MANUFACT_ID,
    COALESCE(I_CONTAINER,'UNKNOWN') AS CONTAINER,
    COALESCE(I_CATEGORY,'UNKNOWN') AS CATEGORY,
    I_MANAGER_ID AS MANAGER_ID
FROM {{ source('raw', 'item') }}