--SELECT LISTAGG('- name: '|| SUBSTR(COLUMN_NAME, 4), '\n')
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'CUSTOMER_ADDRESS';
SELECT
    COALESCE(CA_SUITE_NUMBER,'UNKNOWN') AS SUITE_NUMBER,
    CA_LOCATION_TYPE AS LOCATION_TYPE,
    COALESCE(CA_STATE,'UNKNOWN') AS STATE,
    COALESCE(CA_STREET_TYPE,'UNKNOWN') AS STREET_TYPE,
    CAST(CA_ADDRESS_SK AS VARCHAR) AS ADDRESS_SK,
    COALESCE(CA_COUNTY,'UNKNOWN') AS COUNTY,
    COALESCE(CA_STREET_NUMBER,'UNKNOWN') AS STREET_NUMBER,
    COALESCE(CA_COUNTRY,'UNKNOWN') AS COUNTRY,
    CA_GMT_OFFSET AS GMT_OFFSET,
    COALESCE(CA_CITY,'UNKNOWN') AS CITY,
    COALESCE(CA_ADDRESS_ID,'UNKNOWN') AS ADDRESS_ID,
    COALESCE(CA_ZIP,'UNKNOWN') AS ZIP,
    COALESCE(CA_STREET_NAME,'UNKNOWN') AS STREET_NAME
FROM {{ source('raw', 'customer_address') }}